### ISSUE TITLE
Implement onboarding flow based on design

### ISSUE THREAD

**Issue by shovan777** [atharvatechnology/Apex-app#1]
## Overview

With this feature user will be onbaorded into the app. User will be able to login/signup based on phone number. The whole flow should be closely coupled with the flow that is implemented in the web app.

#### Intended Outcome

- User is able to see the onboarding screen
- able to signup and login based on phone number
- verify with otp

## Prerequisite features
- [x] #2
- [x] #3
- [x] #5
- [x] #19 

## References
- [design](https://www.figma.com/file/P38nvCDlhyVtfORvd1D22q/mobile?node-id=0%3A1)

**Comment by tyagisen** [comment]
Please only close the issue if all the pererequisite tasks have been complete. In this case, #3 and other tasks are not complete.
